parser: babel-eslint
env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends:
- 'eslint:recommended'
- 'airbnb'
- 'plugin:react/recommended'
- 'plugin:flowtype/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: false
  sourceType: module
plugins:
- react
- flowtype
rules:
  "no-lonely-if": 0
  "no-unused-vars": 0
  "import/no-extraneous-dependencies": 0
  "jsx-a11y/click-events-have-key-events": 0
  "jsx-a11y/no-noninteractive-element-interactions": 0
  "react/jsx-one-expression-per-line": 0
  "no-case-declarations": 0
  "import/prefer-default-export": 0
  "react/prefer-stateless-function": 0
  "jsx-a11y/label-has-associated-control": 0
  "jsx-a11y/label-has-for": 0
